import type { AppData } from '@/types';

export const initialDemoData: AppData = {
  shops: [
    {
      id: 'shop-1',
      name: 'محل النجم الساطع لقطع غيار تويوتا',
      ownerName: 'عبد الله الفيتوري',
      phone: '0912345678',
      city: 'tripoli',
      area: 'تاجوراء',
      openingBalance: 12500,
      createdAt: '2026-01-10',
    },
    {
      id: 'shop-2',
      name: 'مركز الأندلس لقطع غيار كيا وهيونداي',
      ownerName: 'محمود الورفلي',
      phone: '0923456789',
      city: 'tripoli',
      area: 'حي الأندلس',
      openingBalance: 8200,
      createdAt: '2026-01-15',
    },
    {
      id: 'shop-3',
      name: 'شركة برقة لخدمات وصيانة السيارات',
      ownerName: 'سالم المجبري',
      phone: '0918765432',
      city: 'banghazi',
      area: 'الفويهات',
      openingBalance: 19400,
      createdAt: '2026-01-20',
    },
    {
      id: 'shop-4',
      name: 'مؤسسة الساحل لقطع غيار نيسان وهوندا',
      ownerName: 'عمر القرقني',
      phone: '0929876543',
      city: 'misrata',
      area: 'قصر أحمد',
      openingBalance: 5600,
      createdAt: '2026-02-01',
    },
    {
      id: 'shop-5',
      name: 'محل الصمود لقطع الغيار الأصلية',
      ownerName: 'فتحي الزاوي',
      phone: '0915554433',
      city: 'zawia',
      area: 'المركز',
      openingBalance: 3200,
      createdAt: '2026-02-05',
    },
  ],
  payments: [
    {
      id: 'pay-1',
      shopId: 'shop-1',
      amount: 4500,
      method: 'cash',
      date: '2026-02-10',
      note: 'دفعة نقدية عن فواتير شهر يناير',
      createdBy: 'user-admin',
    },
    {
      id: 'pay-2',
      shopId: 'shop-3',
      amount: 8000,
      method: 'bank',
      date: '2026-02-12',
      note: 'تحويل مصرفي - مصرف التجارة والتنمية',
      createdBy: 'user-admin',
    },
  ],
  shipments: [
    {
      id: 'ship-1',
      ref: 'CN-GZ-2026-01',
      departureDate: '2026-01-05',
      arrivalDate: '2026-02-18',
      status: 'arrived',
      totalCostCny: 185000,
      totalShippingCny: 42000,
      cnyToLydRate: 0.72,
      itemCount: 1450,
    },
    {
      id: 'ship-2',
      ref: 'CN-NB-2026-02',
      departureDate: '2026-01-25',
      arrivalDate: '2026-03-05',
      status: 'in_transit',
      totalCostCny: 240000,
      totalShippingCny: 58000,
      cnyToLydRate: 0.73,
      itemCount: 2200,
    },
    {
      id: 'ship-3',
      ref: 'CN-GZ-2025-12',
      departureDate: '2025-11-20',
      arrivalDate: '2025-12-28',
      status: 'cleared',
      totalCostCny: 160000,
      totalShippingCny: 35000,
      cnyToLydRate: 0.71,
      itemCount: 1100,
    },
  ],
  inventory: [
    {
      id: 'inv-item-1',
      oem: '04465-0K090',
      description: 'طقم فحمات فرامل أمامية - تويوتا هايلوكس / فورتشنر',
      carModel: 'Toyota Hilux 2016-2024',
      category: 'فرامل',
      shelf: 'A-12',
      stock: 45,
      minStock: 10,
      purchasePrice: 65,
      sellPrice: 110,
      shipmentId: 'ship-1',
    },
    {
      id: 'inv-item-2',
      oem: '90919-01164',
      description: 'شمعات احتراق إيريديوم - تويوتا كامري / كورولا',
      carModel: 'Toyota Camry / Corolla',
      category: 'كهرباء ومحرك',
      shelf: 'B-04',
      stock: 120,
      minStock: 25,
      purchasePrice: 18,
      sellPrice: 35,
      shipmentId: 'ship-1',
    },
    {
      id: 'inv-item-3',
      oem: '58101-1RA00',
      description: 'فحمات فرامل أمامية - هيونداي أكسنت / إلنترا',
      carModel: 'Hyundai Accent 2012-2020',
      category: 'فرامل',
      shelf: 'A-08',
      stock: 30,
      minStock: 15,
      purchasePrice: 48,
      sellPrice: 85,
      shipmentId: 'ship-1',
    },
    {
      id: 'inv-item-4',
      oem: '26300-35505',
      description: 'فلتر زيت أصلي - هيونداي / كيا محركات 1.6 - 2.0',
      carModel: 'Hyundai / Kia All Models',
      category: 'فلاتر وزيوت',
      shelf: 'C-02',
      stock: 8,
      minStock: 20,
      purchasePrice: 14,
      sellPrice: 28,
      shipmentId: 'ship-3',
    },
    {
      id: 'inv-item-5',
      oem: '48510-09L10',
      description: 'مساعد أمامي يمين - تويوتا كورولا 2014-2019',
      carModel: 'Toyota Corolla 2014-2019',
      category: 'هيكل وعفشة',
      shelf: 'D-15',
      stock: 18,
      minStock: 6,
      purchasePrice: 145,
      sellPrice: 240,
      shipmentId: 'ship-1',
    },
    {
      id: 'inv-item-6',
      oem: '27060-0T020',
      description: 'دينمو شحن 12V 100A - تويوتا يارس / كورولا',
      carModel: 'Toyota Yaris / Corolla',
      category: 'كهرباء ومحرك',
      shelf: 'E-03',
      stock: 4,
      minStock: 5,
      purchasePrice: 290,
      sellPrice: 450,
      shipmentId: 'ship-3',
    },
    {
      id: 'inv-item-7',
      oem: '81110-02B50',
      description: 'مصباح أمامي LED يمين - تويوتا كورولا 2020+',
      carModel: 'Toyota Corolla 2020+',
      category: 'إضاءة وبودي',
      shelf: 'F-01',
      stock: 12,
      minStock: 4,
      purchasePrice: 380,
      sellPrice: 590,
      shipmentId: 'ship-1',
    },
  ],
  invoices: [
    {
      id: 'inv-rec-1',
      number: 'INV-0001',
      shopId: 'shop-1',
      shopName: 'محل النجم الساطع لقطع غيار تويوتا',
      date: '2026-02-08',
      lines: [
        {
          itemId: 'inv-item-1',
          oem: '04465-0K090',
          description: 'طقم فحمات فرامل أمامية - تويوتا هايلوكس / فورتشنر',
          qty: 10,
          unitPrice: 110,
          unitCost: 65,
          lineTotal: 1100,
          lineCost: 650,
        },
        {
          itemId: 'inv-item-2',
          oem: '90919-01164',
          description: 'شمعات احتراق إيريديوم - تويوتا كامري / كورولا',
          qty: 20,
          unitPrice: 35,
          unitCost: 18,
          lineTotal: 700,
          lineCost: 360,
        },
      ],
      subtotal: 1800,
      discount: 50,
      total: 1750,
      totalCost: 1010,
      paymentMethod: 'credit',
      paidAmount: 500,
      createdBy: 'user-admin',
      createdByName: 'مدير المبيعات',
      status: 'partial',
    },
    {
      id: 'inv-rec-2',
      number: 'INV-0002',
      shopId: 'shop-2',
      shopName: 'مركز الأندلس لقطع غيار كيا وهيونداي',
      date: '2026-02-11',
      lines: [
        {
          itemId: 'inv-item-3',
          oem: '58101-1RA00',
          description: 'فحمات فرامل أمامية - هيونداي أكسنت / إلنترا',
          qty: 6,
          unitPrice: 85,
          unitCost: 48,
          lineTotal: 510,
          lineCost: 288,
        },
        {
          itemId: 'inv-item-5',
          oem: '48510-09L10',
          description: 'مساعد أمامي يمين - تويوتا كورولا 2014-2019',
          qty: 2,
          unitPrice: 240,
          unitCost: 145,
          lineTotal: 480,
          lineCost: 290,
        },
      ],
      subtotal: 990,
      discount: 0,
      total: 990,
      totalCost: 578,
      paymentMethod: 'cash',
      paidAmount: 990,
      createdBy: 'user-sales',
      createdByName: 'أحمد المندوب',
      status: 'paid',
    },
  ],
  vehicles: [
    {
      id: 'veh-1',
      name: 'شاحنة توزيع طرابلس 1 (إيسوزو)',
      plateNumber: '5-12849',
      type: 'شاحنة صغيرة',
      model: 'Isuzu NPR 2022',
      status: 'active',
      createdAt: '2026-01-01',
    },
    {
      id: 'veh-2',
      name: 'فان توزيع بنغازي (تويوتا هايس)',
      plateNumber: '8-44912',
      type: 'فان بضاعة',
      model: 'Toyota Hiace 2021',
      status: 'active',
      createdAt: '2026-01-05',
    },
  ],
  trips: [
    {
      id: 'trip-1',
      driverName: 'طارق الزنتاني',
      vehicle: 'شاحنة توزيع طرابلس 1 (إيسوزو)',
      vehicleId: 'veh-1',
      departureAt: '2026-02-14 08:30',
      status: 'active',
      totalSales: 2740,
      city: 'tripoli',
      area: 'تاجوراء وعين زارة',
      notes: 'جولة توزيع الصباح لمحلات تاجوراء',
      createdBy: 'user-admin',
      createdByName: 'مدير المبيعات',
      createdAt: '2026-02-14T08:30:00',
      items: [
        {
          id: 'ti-1',
          tripId: 'trip-1',
          itemId: 'inv-item-1',
          oem: '04465-0K090',
          description: 'طقم فحمات فرامل أمامية - تويوتا هايلوكس / فورتشنر',
          loadedQty: 20,
          soldQty: 12,
          returnedQty: 0,
          unitPrice: 110,
          unitCost: 65,
        },
        {
          id: 'ti-2',
          tripId: 'trip-1',
          itemId: 'inv-item-2',
          oem: '90919-01164',
          description: 'شمعات احتراق إيريديوم - تويوتا كامري / كورولا',
          loadedQty: 40,
          soldQty: 30,
          returnedQty: 0,
          unitPrice: 35,
          unitCost: 18,
        },
      ],
    },
  ],
  stockMovements: [
    {
      id: 'sm-1',
      itemId: 'inv-item-1',
      oem: '04465-0K090',
      description: 'طقم فحمات فرامل أمامية - تويوتا هايلوكس / فورتشنر',
      type: 'load_vehicle',
      qty: 20,
      source: 'main_warehouse',
      target: 'vehicle',
      vehicleId: 'veh-1',
      vehicleName: 'شاحنة توزيع طرابلس 1 (إيسوزو)',
      tripId: 'trip-1',
      notes: 'تحميل بداية الجولة',
      createdAt: '2026-02-14T08:35:00',
      createdBy: 'user-admin',
      createdByName: 'مدير المبيعات',
    },
    {
      id: 'sm-2',
      itemId: 'inv-item-2',
      oem: '90919-01164',
      description: 'شمعات احتراق إيريديوم - تويوتا كامري / كورولا',
      type: 'load_vehicle',
      qty: 40,
      source: 'main_warehouse',
      target: 'vehicle',
      vehicleId: 'veh-1',
      vehicleName: 'شاحنة توزيع طرابلس 1 (إيسوزو)',
      tripId: 'trip-1',
      notes: 'تحميل بداية الجولة',
      createdAt: '2026-02-14T08:35:00',
      createdBy: 'user-admin',
      createdByName: 'مدير المبيعات',
    },
    {
      id: 'sm-3',
      itemId: 'inv-item-1',
      oem: '04465-0K090',
      description: 'طقم فحمات فرامل أمامية - تويوتا هايلوكس / فورتشنر',
      type: 'vehicle_sale',
      qty: 12,
      source: 'vehicle',
      target: 'customer',
      vehicleId: 'veh-1',
      vehicleName: 'شاحنة توزيع طرابلس 1 (إيسوزو)',
      tripId: 'trip-1',
      shopId: 'shop-1',
      shopName: 'محل النجم الساطع لقطع غيار تويوتا',
      notes: 'مبيعات جولة تاجوراء',
      createdAt: '2026-02-14T10:15:00',
      createdBy: 'user-admin',
      createdByName: 'مدير المبيعات',
    },
    {
      id: 'sm-4',
      itemId: 'inv-item-2',
      oem: '90919-01164',
      description: 'شمعات احتراق إيريديوم - تويوتا كامري / كورولا',
      type: 'vehicle_sale',
      qty: 30,
      source: 'vehicle',
      target: 'customer',
      vehicleId: 'veh-1',
      vehicleName: 'شاحنة توزيع طرابلس 1 (إيسوزو)',
      tripId: 'trip-1',
      shopId: 'shop-2',
      shopName: 'مركز الأندلس لقطع غيار كيا وهيونداي',
      notes: 'مبيعات جولة تاجوراء',
      createdAt: '2026-02-14T11:45:00',
      createdBy: 'user-admin',
      createdByName: 'مدير المبيعات',
    },
  ],
};
